language: node_js
node_js:
- 12

services:
- docker

before_install:
- echo "nothing needs to be installed"

install:
- echo "nothing needs to be installed"

before_script:
- echo "no tests"


script:
- docker --version # print the version for logging
- docker-compose -f docker-compose-build.yaml build --parallel
- docker tag udagram-api-feed docker4mathenge/udagram-api-feed:v1
- docker tag udagram-api-user docker4mathenge/udagram-api-user:v1
- docker tag udagram-frontend docker4mathenge/udagram-frontend:v1
- docker tag reverseproxy docker4mathenge/reverseproxy:v1


after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push docker4mathenge/udagram-api-feed:v1
- docker push docker4mathenge/udagram-api-user:v1
- docker push docker4mathenge/udagram-frontend:v1
- docker push docker4mathenge/reverseproxy:v1
